"use server";

import { revalidatePath } from "next/cache";
import { requireAgent } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { audit } from "@/lib/audit";
import { notify, notifyAdmins } from "@/lib/notifications";
import { renderDocumentPdf } from "@/lib/pdf";
import { storage } from "@/lib/storage";
import { cpdCycleMonths } from "@/lib/placement";
import { issueSubscriptionInvoice, issueCpdRefreshInvoice } from "@/lib/billing";
import { formatDate } from "@/lib/format";
import { welfareMethodLabels, wellbeingMeta } from "@/lib/constants";
import type { FormState } from "@/lib/forms";
import type { WelfareMethod, WellbeingStatus } from "@/generated/prisma/client";

/** Logs a welfare check and emails a generated welfare report to the employer (brief §8.2/§10.1). */
export async function logWelfareCheck(_prev: FormState, formData: FormData): Promise<FormState> {
  const agent = await requireAgent();
  const placementId = String(formData.get("placementId") || "");
  const method = String(formData.get("method") || "CALL") as WelfareMethod;
  const wellbeing = String(formData.get("wellbeing") || "GREEN") as WellbeingStatus;
  const attendanceConfirmed = formData.get("attendanceConfirmed") === "on";
  const issues = String(formData.get("issues") || "").trim();
  const actionTaken = String(formData.get("actionTaken") || "").trim();

  const placement = await prisma.placement.findUnique({
    where: { id: placementId },
    include: { worker: { include: { user: true } }, employer: { include: { user: true } }, job: true },
  });
  if (!placement) return { ok: false, message: "Placement not found." };

  // Generate a branded welfare report PDF.
  const pdf = await renderDocumentPdf({
    title: "Monthly Welfare Report",
    subtitle: `${placement.roleTitle} · ${placement.worker.user.name}`,
    body: [
      `DATE\n${formatDate(new Date())}`,
      `WORKER\n${placement.worker.user.name} — ${placement.roleTitle}`,
      `CHECK METHOD\n${welfareMethodLabels[method]}`,
      `ATTENDANCE CONFIRMED\n${attendanceConfirmed ? "Yes" : "No"}`,
      `CARE RECIPIENT WELLBEING\n${wellbeingMeta[wellbeing].label}`,
      `ISSUES FLAGGED\n${issues || "None"}`,
      `ACTION TAKEN\n${actionTaken || "Routine check — no action required."}`,
      `ACCOUNT MANAGER\n${agent.name}`,
    ].join("\n\n"),
    footer: "Generated by Oakvale Jobs · jobs.oakvaleltd.com",
  }).catch(() => null);

  let reportPdfKey: string | null = null;
  let reportPdfUrl: string | null = null;
  if (pdf) {
    const stored = await storage.saveBytes(pdf, { folder: "welfare", fileName: "welfare-report.pdf" });
    reportPdfKey = stored.key;
    reportPdfUrl = stored.url;
  }

  await prisma.welfareCheck.create({
    data: {
      placementId,
      agentId: agent.id,
      method,
      attendanceConfirmed,
      wellbeing,
      issues: issues || null,
      actionTaken: actionTaken || null,
      reportPdfKey,
      reportPdfUrl,
    },
  });

  await audit({ userId: agent.id, action: "welfare.logged", entityType: "Placement", entityId: placementId, meta: { wellbeing } });

  // Email the welfare report to the employer.
  await notify({
    userId: placement.employer.userId,
    type: "welfare.report",
    title: "Welfare report available",
    body: `A welfare report for ${placement.worker.user.name} (${placement.roleTitle}) is available. Status: ${wellbeingMeta[wellbeing].label}.`,
    link: `/employer/placements/${placementId}`,
    email: true,
  });

  // Amber/Red raises an escalation task for the team (brief §8.2).
  if (wellbeing !== "GREEN") {
    await notifyAdmins({
      type: "welfare.escalation",
      title: `Welfare escalation (${wellbeing}) — ${placement.worker.user.name}`,
      body: `${agent.name} flagged a ${wellbeingMeta[wellbeing].label} welfare status. Log action taken within 24 hours.`,
      link: `/agent/placements/${placementId}`,
    });
  }

  revalidatePath(`/agent/placements/${placementId}`);
  revalidatePath(`/employer/placements/${placementId}`);
  return { ok: true, message: "Welfare check logged and report sent to the employer." };
}

/** Records a CPD refresh completion and resets the next-due date. */
export async function markCpdComplete(placementId: string, workerId: string) {
  const agent = await requireAgent();
  const worker = await prisma.workerProfile.findUnique({
    where: { id: workerId },
    include: { workforceCategory: true },
  });
  if (!worker) return;

  const now = new Date();
  const next = new Date(now);
  next.setMonth(next.getMonth() + cpdCycleMonths(worker.workforceCategory?.config));
  await prisma.workerProfile.update({
    where: { id: workerId },
    data: { cpdLastCompletedAt: now, cpdNextDueAt: next },
  });

  // Recompute searchability (an overdue worker may become searchable again).
  const { recomputeWorkerCompletion } = await import("@/lib/worker");
  await recomputeWorkerCompletion(workerId);

  await audit({ userId: agent.id, action: "cpd.completed", entityType: "WorkerProfile", entityId: workerId });
  await notify({
    userId: worker.userId,
    type: "cpd.completed",
    title: "CPD refresh recorded",
    body: `Your CPD is up to date. Next refresh due ${formatDate(next)}.`,
  });

  // Bill the employer for the CPD refresh (annually per placed worker, brief §10.2).
  const invoice = await issueCpdRefreshInvoice(placementId);
  if (invoice) {
    const placement = await prisma.placement.findUnique({
      where: { id: placementId },
      include: { employer: { select: { userId: true } } },
    });
    if (placement) {
      await audit({ userId: agent.id, action: "invoice.issued", entityType: "Invoice", entityId: invoice.id, meta: { type: "CPD_REFRESH" } });
      await notify({
        userId: placement.employer.userId,
        type: "invoice.issued",
        title: `Invoice ${invoice.number} — CPD refresh fee`,
        body: `A CPD refresh invoice of ₦${invoice.amount.toLocaleString()} is now due (30-day terms).`,
        link: "/employer/billing",
        email: true,
      });
    }
  }

  revalidatePath(`/agent/placements/${placementId}`);
  revalidatePath("/employer/billing");
}

/** Issues the annual partnership subscription invoice for a corporate employer (brief §10.2). */
export async function issueEmployerSubscription(employerId: string): Promise<FormState> {
  const agent = await requireAgent();
  const invoice = await issueSubscriptionInvoice(employerId);
  if (!invoice) return { ok: false, message: "Employer not found." };

  const employer = await prisma.employerProfile.findUnique({
    where: { id: employerId },
    include: { user: { select: { id: true } } },
  });

  await audit({ userId: agent.id, action: "invoice.issued", entityType: "Invoice", entityId: invoice.id, meta: { type: "SUBSCRIPTION" } });
  if (employer) {
    await notify({
      userId: employer.user.id,
      type: "invoice.issued",
      title: `Invoice ${invoice.number} — annual subscription`,
      body: `Your annual partnership subscription invoice of ₦${invoice.amount.toLocaleString()} is now due (30-day terms).`,
      link: "/employer/billing",
      email: true,
    });
  }

  revalidatePath("/agent/accounts");
  revalidatePath("/employer/billing");
  return { ok: true, message: `Subscription invoice ${invoice.number} issued.` };
}

/** Assigns (or reassigns) an account manager to an employer account. */
export async function assignAccountManager(employerId: string, agentId: string) {
  await requireAgent();
  await prisma.employerProfile.update({ where: { id: employerId }, data: { assignedAgentId: agentId || null } });
  revalidatePath("/agent/accounts");
}
